apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lab8
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - lab8
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: (api-gateway|user-service|product-service|order-service)
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: service
