apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      enableServiceLinks: false
      containers:
      - name: product-service
        image: product-service:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: lab8-config
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: lab8-mongo
              key: PRODUCT_MONGO_URI
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
